### ISSUE TITLE
Task Tracker

### ISSUE THREAD

**Issue by sancarn** [LaunchMenu/LaunchMenu#120]
## Description

An applet with a simple task tracker. In an ideal world this would be usable as a simple Todo tracker, as well as boasting features for more complex business-style tasks.

### Create tasks [MVP]

Simple ability to create new tasks. Give them a name and perhaps ability to tag a category.

Potential pattern:

```
//Maybe make regex customisable even and store captured names in metadata?
T+ (?:(?<Category>\w+)\s*-\s*)?(?<Task>.*)) 
```

Examples:

```
T+ School - Math homework
T+ Washing
``` 

### Tag tasks [MVP]

Ability to tag additional keywords to tasks (similar to github labels in issues tracker)

### Task status (Completed / Delayed)

* Simple ability to mark tasks as complete. [MVP]
* Simple ability to mark tasks as defferred

### Task deletion [MVP]

Simple ability to delete tasks when no longer needed / when completed.

### Task categorisation

Categorisation like notes would be useful. Implementing tags like categories might be beneficial also.

### Ability to add metadata to a task

This can be buried in an advanced menu, but metadata (and potentially defining a metadata structure/spec) could be very useful for other dynamic parts of this application. Ability to define metadata and potentially even set up automated means of obtaining specific metadata, might be beneficial.

### Dynamic priority (e.g. deadlines)

As a deadline approaches the hope would be that the task priority gets larger and larger. There may be other situations where dynamic priority is required (e.g. based off of the weather (turn off plant watering system if wet weather) or other services). For this reason it would be good to add the ability to add a custom Javascript function option. 

### Recurring tasks

Some tasks may be recurring. Setting up simple recurrence rules like "daily", "monthly", "annually" would be great. Again there may be other situations where more complex recurrences can occur which we don't think about. e.g. the 6th working day after the start of the month (note this may also have to take into consideration bank holidays and therefore query a government site). For this reason it'd be great to allow a recurring task to execute a custom JS function.

### Track time it takes to complete a task [MVP]

A simple and quick way to "start working on a task" and "stop/switch work to a new/existing task". Generally speaking this could be used as a way of tracking time like a labelled stopwatch and can have tasks such as "Call with Anthony" to track how long you typically spend on calls with Anthony.

While tracking time it may be useful to track the names ot the windows which have focus, and optionally screenshot them? I can see this being useful for investigating the true time it took for you to complete a task. Definitely need to have this as a **default off** option though due to privacy concerns.

### Alerts

Ability to alert the user when a task is due. Similar to before determining "due" status could have some build in options but a custom js function may also be beneficial. Also the ability to easily customise the alert which is given. Most people like a simple notification in the top left hand side of the screen, i personally prefer the whole screen to flash a particular color. 

### Adding next steps to existing tasks

Often after completing a task you will have next steps. E.G.

```
* [ ] Create Finance database line
  * [ ] Create purchase order
    * [ ] Inform supplier of PO reference
    * [ ] Await invoice
      * [ ]  Receipt purchase order
```

It would be nice to be able to link these tasks together so you have an audit trail. I would imagine this as an action on a menu item "Complete and create next steps".

### Obtain new tasks

Similar to creating new tasks, but in this scenario it'd be nice to be able to set up some javascript which would run to obtain new tasks for you. Whether it be from a database or from an API for your business etc.
