### ISSUE TITLE
FileSystem search applet

### ISSUE THREAD

**Issue by sancarn** [LaunchMenu/LaunchMenu#82]
The ability to search the file system for files in LM.

## Requirements

* Choose BFS (bredth first search) or DFS (depth first search)
* Ability to cancel out whole trees of directories given a condition
* Regex searching via file name
* Regex searching via file contents searching (this might be a seperate applet plugin?)
* Ideally Dynamic (updates as files change in background)
* A plugin system.
* File class to be extendable and matchable to multiple files simultaneously or folders of files. E.G. The following is a shape file, but comprises of 2 seperate files a `.shp` and a `.dbf`. Would want to be able to move them together, instead of individually etc. Would want to have them appear as 1 file (via a plugin) instead of 2 files.
  ```
  some/file.shp
  some/file.dbf
  ```
* To be able to match a folder structure as a single `File` also e.g. a sewer asset survey:
  ```
  someID
  |- someID.docx
  |- someID-in.jpg
  |- someID-out.jpg
  |- someID-chamber.jpg
  |- telemetry
  |  |- dropTests.pdf
  |  |- scada
  ...
  ```
* A simple `run` command for launching applications `run:notepad`.

## Roadmap

Just a high level roadmap currently

* [ ] Design and implement VFS model for efficient searching.
* [ ] Design and implement query object for search criteria
* [ ] Design and implement query search syntax to convert to query object
